//----------------------------------------------------
// code was generated by JCUP V0.12
// Fri Feb 12 12:15:54 GMT+10:30 1999
//----------------------------------------------------

package jcup;

/** JavaCUP generated class containing interface constants */
public interface sym {
  /* terminals */
  static final int PERCENT_PREC = 24;
  static final int SCAN = 10;
  static final int RIGHT = 22;
  static final int PRECEDENCE = 20;
  static final int LEFT = 21;
  static final int CODE_STRING = 28;
  static final int COLON = 17;
  static final int NONASSOC = 23;
  static final int BAR = 19;
  static final int STAR = 15;
  static final int LBRACK = 25;
  static final int WITH = 11;
  static final int SEMI = 13;
  static final int PARSER = 6;
  static final int CODE = 4;
  static final int COMMA = 14;
  static final int INIT = 9;
  static final int EOF = 0;
  static final int COLON_COLON_EQUALS = 18;
  static final int PACKAGE = 2;
  static final int error = 1;
  static final int IMPORT = 3;
  static final int RBRACK = 26;
  static final int START = 12;
  static final int NON = 8;
  static final int ACTION = 5;
  static final int DOT = 16;
  static final int ID = 27;
  static final int TERMINAL = 7;
};

