//----------------------------------------------------
// code was generated by JCUP V0.13
// Mon Feb 15 11:17:01 GMT+10:30 1999
//----------------------------------------------------

package jaco.join.grammar;

/** JavaCUP generated class containing interface constants */
public interface Symbols {
  /* terminals */
  static final int EQ = 15;
  static final int PLUS = 11;
  static final int FALSE = 27;
  static final int BAR = 29;
  static final int STRLIT = 37;
  static final int AMPERSAND = 4;
  static final int EQUALS = 7;
  static final int TRUE = 26;
  static final int MINUS = 12;
  static final int GT = 17;
  static final int TIMES = 13;
  static final int FLOATLIT = 35;
  static final int INTLIT = 33;
  static final int LBRACE = 9;
  static final int ELSE = 25;
  static final int COMMA = 8;
  static final int LPAREN = 2;
  static final int SUB = 30;
  static final int EOF = 0;
  static final int GTEQ = 19;
  static final int error = 1;
  static final int LONGLIT = 34;
  static final int NOTEQ = 16;
  static final int ERROR = 28;
  static final int DIV = 14;
  static final int IDENTIFIER = 38;
  static final int NOT = 23;
  static final int CHARLIT = 32;
  static final int RBRACE = 10;
  static final int LTEQ = 20;
  static final int RPAREN = 3;
  static final int LT = 18;
  static final int USUB = 31;
  static final int IF = 24;
  static final int DOT = 6;
  static final int AND = 21;
  static final int DOUBLELIT = 36;
  static final int OR = 22;
  static final int SEMICOLON = 5;
};

